server:
  port: 5500

spring:
  datasource:
    url : jdbc:postgresql://192.168.50.222:5432/casaos
    driverClassName: org.postgresql.Driver
    username: casaos
    password: casaos
  jpa:
    hibernate.ddl-auto: create-drop
  kafka:
    bootstrap-servers: 192.168.50.222:9092

bulk.data:
  partitionSize: 200
  commitSize: 500
